from datetime import time

ASSET_TYPE_FUTURES = "futures"
ASSET_TYPE_CRYPTO = "crypto"
ASSET_TYPE_STOCK = "stock"

FUTURES_SYMBOL_SUFFIX = "=F"
CRYPTO_SYMBOL_SUFFIXES = ("-USD", "-USDT")

DEFAULT_SESSION_TIMEZONE_BY_ASSET = {
    ASSET_TYPE_FUTURES: "America/New_York",
    ASSET_TYPE_CRYPTO: "UTC",
    ASSET_TYPE_STOCK: "America/New_York",
}

DEFAULT_SESSION_START_BY_ASSET = {
    ASSET_TYPE_FUTURES: "18:00",
    ASSET_TYPE_CRYPTO: "00:00",
    ASSET_TYPE_STOCK: "04:00",
}

DEFAULT_MARKET_POLL_INTERVAL_SECONDS = 5

YFINANCE_QUOTE_PRIMARY_PERIOD = "2d"
YFINANCE_QUOTE_PRIMARY_INTERVAL = "1m"
YFINANCE_QUOTE_FALLBACK_PERIOD = "5d"
YFINANCE_QUOTE_FALLBACK_INTERVAL = "5m"
YFINANCE_DAILY_HISTORY_PERIOD = "10d"
YFINANCE_DAILY_HISTORY_INTERVAL = "1d"
YFINANCE_PREV_5M_PERIOD = "5d"
YFINANCE_PREV_5M_INTERVAL = "5m"
YFINANCE_DAILY_BAR_INTERVAL = "1d"

MARKET_HISTORY_DEFAULT_RANGE = "1d"
MARKET_HISTORY_YEAR_RANGE = "1y"
MARKET_HISTORY_INTRADAY_PERIOD = "5d"
MARKET_HISTORY_INTRADAY_INTERVAL = "5m"
MARKET_HISTORY_YEAR_BAR_LIMIT = 252
MARKET_HISTORY_YEAR_SEED_PERIOD = "2y"
MARKET_HISTORY_YEAR_REFRESH_PERIOD = "1mo"
MARKET_HISTORY_INTRADAY_FRESH_MINUTES = 5
MARKET_HISTORY_YEAR_FRESH_DAYS = 4
DAILY_BAR_REFRESH_LAG_DAYS = 1

TRUTH_SOCIAL_DEFAULT_LIMIT = 10
TRUTH_SOCIAL_MAX_LIMIT = 20
TRUTH_SOCIAL_FETCH_FLOOR = 20
TRUTH_SOCIAL_SUMMARY_LIMIT = 260
TRUTH_SOCIAL_ACTIVE_START = time(4, 0)
TRUTH_SOCIAL_ACTIVE_END = time(16, 0)
TRUTH_SOCIAL_ACTIVE_REFRESH_MINUTES = 1
TRUTH_SOCIAL_IDLE_REFRESH_MINUTES = 10

WIRE_NEWS_DEFAULT_LIMIT = 10
WIRE_NEWS_MAX_LIMIT = 30
WIRE_NEWS_CACHE_TTL_SECONDS = 600
